### ISSUE TITLE
Build Error When  pallet airdrop is merged into web3labs 

### ISSUE THREAD

**Issue by ibrizsabin** [ibriz/ice-substrate#20]
The web3labs main branch and pallet airdrop compiles fine separately but when pallet airdrop is merged into web3labs or added as dependecy in web3labs the build fails with following error:
` --> /workspace/.cargo/git/checkouts/substrate-7e08433d4c370a21/158cdfd/primitives/runtime-interface/src/impls.rs:45:1
   |
45 | assert_eq_size!(usize, u32);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `usize` (64 bits)
   = note: target type: `u32` (32 bits)
   = note: this error originates in the macro `assert_eq_size` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> /workspace/.cargo/git/checkouts/substrate-7e08433d4c370a21/158cdfd/primitives/runtime-interface/src/impls.rs:47:1
   |
47 | assert_eq_size!(*const u8, u32);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: source type: `*const u8` (64 bits)
   = note: target type: `u32` (32 bits)
   = note: this error originates in the macro `assert_eq_size` (in Nightly builds, run with -Z macro-backtrace for more info)`
   
   When searched thorugh similar issues faced by others it looks like this occurs when we forget to add std as feature when using parity crates. we have combed through all the toml files to find any such missing imports but std is included in all parity dependencies. Other than this we have tried building with following toolchains as well:
-  * Using rustc `nightly-2022-01-16` with `stable-1.61` & `stable-1.58`
- * Using nightly `nightly-2022-01-10` with `stable-1.61` & `stable-1.58`
The issue can be reproduced if we run build on branch `build-error`.

**Comment by sudipghimire533** [comment]
Sucess build prototyped at:
https://github.com/sudipghimire533/ice-substrate/tree/build
